services:
  nginx:
    image: nginx:latest
    container_name: nginx-ssl
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src:/var/www/html:ro
      - ../.certs:/etc/ssl/certs:ro
    restart: unless-stopped
