services:
  nginx:
    image: nginx:alpine
    container_name: nginx-ssl
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./:/app:ro
      - ../.certs:/etc/ssl/certs:ro
    restart: unless-stopped
