name: Update

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: assume aws role
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::533267027805:role/beast
          output-credentials: true

      - name: update server
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceids,Values=i-09de9f5b6dc5f9df6" \
            --parameters "commands=[
              \"#!/bin/bash\",
              \"docker stop nginx\",
              \"docker rm nginx\",
              \"rm -rf /home/ubuntu/ethanrohman\",
              \"cd /home/ubuntu\",
              \"git clone https://github.com/EthanRohman93/ethanrohman.git ethanrohman\",
              \"cd /home/ubuntu/ethanrohman\",
              \"git pull origin main\",
              \"docker compose up --build -d\"
            ]" \
            --comment "update server"
            --output text
