name: Deploy

on:
  push:
    branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: .

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: aws credentials
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: terraform init
        run: terraform -chdir=terraform init

      # - name: terraform plan
        # run: terraform plan
        # env:
          # TF_VAR_region: us-east-1
          # TF_VAR_env_prefix: prod
          # TF_VAR_instance_type: t2.micro
          # TF_VAR_ec2_name: ethanrohman
          # TF_VAR_github_pat: ${{ secrets.PAT }}
          # TF_VAR_github_repo: EthanRohman93/ethanrohman
          # TF_VAR_ethanrohman_crt: ${{ secrets.ETHANROHMAN_CRT }}
          # TF_VAR_ethanrohman_key: ${{ secrets.ETHANROHMAN_KEY }}
          # TF_VAR_ethanrohman_bundle: ${{ secrets.ETHANROHMAN_BUNDLE }}

      # - name: terraform apply
        # run: terraform apply -auto-approve
        # env:
          # TF_VAR_region: us-east-1
          # TF_VAR_env_prefix: prod
          # TF_VAR_instance_type: t2.micro
          # TF_VAR_ec2_name: ethanrohman
          # TF_VAR_github_pat: ${{ secrets.PAT }}
          # TF_VAR_github_repo: EthanRohman93/ethanrohman
          # TF_VAR_ethanrohman_crt: ${{ secrets.ETHANROHMAN_CRT }}
          # TF_VAR_ethanrohman_key: ${{ secrets.ETHANROHMAN_KEY }}
          # TF_VAR_ethanrohman_bundle: ${{ secrets.ETHANROHMAN_BUNDLE }}
